name: lyrics_anki_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ankidroid_for_flutter: ^1.0.3
  # envied: ^1.3.1
  archive: ^4.0.7
  file_saver: ^0.3.1
  firebase_ai: ^3.6.1
  firebase_analytics: ^12.1.0
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.3.4
  intl: ">=0.19.0 <0.21.0"
  json_annotation: ^4.8.1
  path: ^1.9.1
  path_provider: ^2.1.2
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.3.3
  shimmer: ^3.0.0
  sqlite3: ^2.9.4
  universal_html: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.9
  # envied_generator: ^1.1.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  hive_ce_generator: ^1.9.2
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  riverpod_generator: ^2.3.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
    - family: Noto Sans Thai
      fonts:
        - asset: assets/fonts/NotoSansThai-Regular.ttf
    - family: Noto Sans Myanmar
      fonts:
        - asset: assets/fonts/NotoSansMyanmar-Regular.ttf
    - family: Noto Sans SC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.ttf
    - family: Noto Sans TC
      fonts:
        - asset: assets/fonts/NotoSansTC-Regular.ttf
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
