name: lyrics_anki_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.3
  intl: ^0.19.0
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.3.4
  path_provider: ^2.1.2
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  firebase_ai: ^3.6.1
  shimmer: ^3.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  ankidroid_for_flutter: ^1.0.3
  # envied: ^1.3.1
  universal_html: ^2.3.0
  google_generative_ai: ^0.4.7
  firebase_app_check: ^0.4.1+3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  riverpod_generator: ^2.3.3
  very_good_analysis: ^5.1.0
  hive_ce_generator: ^1.9.2
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  # envied_generator: ^1.1.1

flutter:
  uses-material-design: true
  generate: true
